title: <p align="center"> Clara Hony Noveli Marpaung </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/claramarpaung/">LinkedIn</a> |
  <a href="https://github.com/claramarpaung">GitHub</a>
  </p>
  
  <p align="justify">
  I am an Undergraduate Statistics Stdudent at Diponegoro University.
  <br><br>
  I am currently a Data Analytics student at MSIB Zenius.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
